### ISSUE TITLE
pytest doesn't run

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/malco#10]
```
tests/test_post_process_results_format.py:6: in <module>
    from malco.post_process.post_process_results_format import ConvertToPhEvalResult
E   ImportError: cannot import name 'ConvertToPhEvalResult' from 'malco.post_process.post_process_results_format' (/Users/cjm/repos/malco/src/malco/post_process/post_process_results_format.py)
```

pycharm also complains

<img width="648" alt="image" src="https://github.com/monarch-initiative/malco/assets/50745/d0495270-4784-4c6d-9650-cb2c8bc1ce2b">

ConvertToPhEvalResult is indeed not in malco.post_process.post_process_results_format

**Comment by justaddcoffee** [comment]
seems to be fixed by #12
