### ISSUE TITLE
Cache results by mondo adapter

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/malco#23]
Use something like memoize to cache results and reduce time, somewhere here:

https://github.com/monarch-initiative/malco/blob/7f91ae8002c633552af59479bad886010bb73710/src/malco/post_process/mondo_score_utils.py#L84-L89

Possibly useful links by @pnrobinson :
https://stackoverflow.com/questions/1988804/what-is-memoization-and-how-can-i-use-it-in-python
https://github.com/monarch-initiative/pyphetools/blob/main/src/pyphetools/creation/variant_manager.py

**Comment by caufieldjh** [comment]
Isn't that what the `lru_cache` on `omim_mappings()` is already doing?

**Comment by leokim-l** [comment]
> Isn't that what the `lru_cache` on `omim_mappings()` is already doing?

I did not know what that was, actually, yes! 

However, it seems like it's still very very slow. Maybe the cache does not persist between multiple function calls? In the current setup, we are calling score_grounded_result() in a for loop in compute_mrr(), see:

https://github.com/monarch-initiative/malco/blob/2a30bb15d8c7f433495283cbc2b6073b628a7c84/src/malco/post_process/compute_mrr.py#L35-L47

The for loop iterates over grounded prompt replies, i.e. number of phenopackets times number of languages times, well, how many diseases are in each differential. A lot of calls. Can we make the cache persist withing calls, maybe as long as compue_mrr has successfully exited?

**Comment by leokim-l** [comment]
Actually, it seems to me like I was off, the cache does persist. But the standard size is 128 elements. I tried running with increased cache size and it seems to be faster, just by looking at it. This needs further testing to be systematic and if we really want to rely on this, especially for larger runs, but it's pointing us in the right direction, I think.

**Comment by justaddcoffee** [comment]
How slow is this now? If it's fast enough we probably should focus on tidying up the the code. 

If it's painfully slow probably we should just multiprocess the for loop (see [here](https://docs.python.org/3/library/multiprocessing.html)) instead of improving caching

**Comment by caufieldjh** [comment]
I should have timed my last run but 2 phenopackets across 5 languages took <10 min.
