### ISSUE TITLE
Not running all phenopackets

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/malco#36]
Reproduced issue pointed out by @justaddcoffee , when running current version of MALCO https://github.com/monarch-initiative/malco/commit/42bab8d0da7f2651a3c28b2c0593d4ae9ecc81cc in branch https://github.com/monarch-initiative/malco/tree/short_letter not all prompts are run. Probably (speculation) an issue with OntoGPT which does not seem to save anywhere when a call fails due to connection issues. 

Input folder contains 4875 prompts:
`% ls jul3_5000ppkts_i_test/prompts/en | wc 
    4875    4875  197585`

whereas in the output directory we have 223 cases:
`% ls jul3_5000ppkts_o_test/raw_results/en/differentials_by_file | wc
     223     223   10478`

Note that I cannot, at the current time, totally exclude connection issues at Charite' and possible issues with the code running in the background with a locked screen (MacOS, running overnight), although initial simple testing seems to suggest this not to be problematic.

**Comment by pnrobinson** [comment]
I am wondering whether the dependence on pheval is really advantagoues? This task should be pretty simple with a Python script and it is not hard to generate the bar plots. Basically, we need the script to look and see if a GPT run was successfully finished, and if not, repeat it after a few seconds.

**Comment by leokim-l** [comment]
Trying a run now with English only and the code in main, to see if similar issue exists there.

**Comment by leokim-l** [comment]
> I am wondering whether the dependence on pheval is really advantagoues? This task should be pretty simple with a Python script and it is not hard to generate the bar plots. Basically, we need the script to look and see if a GPT run was successfully finished, and if not, repeat it after a few seconds.

I don't fully understand/agree with your comment here, Peter. We don't _need_ PhEval, just like we could have written this code in Java or C. 

The idea was to make our life easier, maybe investing some time in learning a carefully designed tool, in order to be _a lot faster_ the next time we use it. Maybe in this we did fail a bit. **BUT, PhEval does not seem to be source of any issues** (except some initial ones during the Hackathon which are far in the past), if we have some issues debugging with or without PhEval is - I think - about the same. 

I would advise against changing it now, we _might_ have not made the world's best design choice at the beginning of May, but changing everything around now means, to some extent, redo the plumbing. Which is conceptually trivial, but we will break some things. I'd rather spend 2 days fixing the existing (decent) code than coding the pipeline from scratch, with no guarantee this will solve the issue we are having.

**Comment by caufieldjh** [comment]
I think this issue should be addressed by https://github.com/monarch-initiative/ontogpt/pull/408 , though it may also help to change the behavior for `malco` such that it doesn't call `ontogpt` as a shell process, because that causes it to consider the run to be complete even if it errors out.

**Comment by leokim-l** [comment]
@justaddcoffee this has been solved by some commit, or rather by fixes in the ontogpt code? I am doing now a test run of the code in 

https://github.com/monarch-initiative/malco/tree/short_letter 

and if successful I can close this issue. However, I'd suggest we somewhere document within MALCO's tickets where the problem was, for future reference 😃 thanks!

**Comment by justaddcoffee** [comment]
yes this is fixed in Ontogpt by https://github.com/monarch-initiative/ontogpt/pull/408

**Comment by caufieldjh** [comment]
Note that if there's some kind of network issue re: the OpenAI API the fix in ontogpt will not solve that - it will just successfully move on to the next prompt and record the error.

**Comment by justaddcoffee** [comment]
+1 thanks 

closing this issue since I was able to run 5k or some ppkts to completion
