### ISSUE TITLE
Add several models

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/malco#37]
Add possibility of using several different LLMs, this may need to happen in OntoGPT

**Comment by justaddcoffee** [comment]
cc: @caufieldjh - I think he was planning on adding support for many other models (including maybe Claude models?) into OntoGPT soon

**Comment by caufieldjh** [comment]
Yes, this is being added in https://github.com/monarch-initiative/ontogpt/pull/373

**Comment by leokim-l** [comment]
https://github.com/monarch-initiative/ontogpt/commit/8e70774b0fe2febe73a6e27fd2c2cae1b8200f0e should be it, further comments can be done there, if needed.
